export const VIEW_EXPENSE_DATA_TEXT =
  '{"status_code":201,"status_message":"","response_data":[{"index":"1","dateOfPurchase":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","nameOfPurchase":"Watertins","expenditureType":"Groceries","paidBy":"GPay","amountSpend":"80","details":"Watertins","dateCreated":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","expenditureId":"","isSynced":""},{"index":"2","dateOfPurchase":"SunJul02202300:00:00GMT+0530(heuredel’Inde)","nameOfPurchase":"Houserent","expenditureType":"Rent","paidBy":"OnlinePayment","amountSpend":"11000","details":"HDFCBankPayment","dateCreated":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","expenditureId":"","isSynced":""},{"index":"3","dateOfPurchase":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","nameOfPurchase":"Currentbill","expenditureType":"Rent","paidBy":"OnlinePayment","amountSpend":"1036","details":"Junemonthcurrent,water,maintenancebillHDFCpayment","dateCreated":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","expenditureId":"","isSynced":""},{"index":"4","dateOfPurchase":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","nameOfPurchase":"Zerodhashares","expenditureType":"Groceries","paidBy":"GPay","amountSpend":"11000","details":"Servicebillandprepaidtobuynewshares","dateCreated":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","expenditureId":"","isSynced":""},{"index":"5","dateOfPurchase":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","nameOfPurchase":"ETMoney","expenditureType":"Groceries","paidBy":"OnlinePayment","amountSpend":"10000","details":"Mutualfunds,missedsipsforJuneandjuly","dateCreated":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","expenditureId":"","isSynced":""},{"index":"6","dateOfPurchase":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","nameOfPurchase":"Carrent","expenditureType":"Rent","paidBy":"GPay","amountSpend":"1800","details":"MayandJunemonthCarrentmoney900+900","dateCreated":"TueJul11202300:00:00GMT+0530(heuredel’Inde)","expenditureId":"","isSynced":""}]}';

export const ADD_EXPENSE_DATA = {
  expense_index: '',
  expenditureId: 638259803774550000,
  dateOfPurchase: '2023-07-26T18:39',
  nameOfPurchase: 'Test Data',
  expenditureType: 'Groceries',
  paidBy: 'Cash',
  amountSpend: '152.52',
  details: 'This is a Test Data for just testing purpose',
  dateCreated: '2023-07-26T14:59:37.455Z',
  isSynced: '1',
  year: 2023,
  month: 7,
};

export const ADD_EXPENSE_DATA_1 = {
  data: [
    {
      key: 'nameOfPurchase',
      inputID: 'nameOfPurchase',
      name: 'Expense Title',
      placeHolder: 'Enter Name/Title of Expense',
      legendTitle: 'Enter Name/Title of Expense',
      hintText: '',
      isError: false,
      value: 'Test',
      isMandatory: true,
    },
    {
      key: 'amountSpend',
      inputID: 'amountSpend',
      name: 'Amount Spend',
      placeHolder: 'Amount Spend',
      legendTitle: 'Amount Spend',
      hintText: '',
      isError: false,
      value: '152.52',
      isNumber: true,
      isMandatory: true,
    },
    {
      key: 'paidBy',
      inputID: 'paidBy',
      name: 'Payment Type',
      placeHolder: 'Payment Type',
      legendTitle: 'Payment Type',
      hintText: '',
      isError: false,
      value: 'Cash',
      isPicker: true,
      pickerData: [
        'Cash',
        'Card Payment',
        'Online Payment',
        'GPay',
        'Phone Pay',
        'PAYTM',
        'Other Mobile Walets',
      ],
      isMandatory: true,
    },
    {
      key: 'dateOfPurchase',
      inputID: 'dateOfPurchase',
      name: 'Purchase Date',
      placeHolder: 'Date of Purchase',
      legendTitle: 'Date of Purchase',
      hintText: '',
      isError: false,
      value: '2023-07-26T18:39',
      isDatePicker: true,
      isMandatory: true,
    },
    {
      key: 'expenditureType',
      inputID: 'expenditureType',
      name: 'Expense Type',
      placeHolder: 'Expenditure Type',
      legendTitle: 'Expenditure Type',
      hintText: '',
      isError: false,
      value: 'Groceries',
      isPicker: true,
      pickerData: [
        'Groceries',
        'Rent',
        'Fun and Entertainment',
        'Street Foods',
      ],
      isMandatory: true,
    },
    {
      key: 'details',
      inputID: 'details',
      name: 'Details',
      placeHolder: 'Details',
      legendTitle: 'Details',
      hintText: '',
      isError: false,
      value: 'This is a test expense',
      isEditor: true,
      isMandatory: true,
    },
  ],
};

export const VIEW_EXPENSE_DATA = {
  status_code: 201,
  status_message: '',
  response_data: [
    {
      index: '1',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Water tins',
      expenditureType: 'Groceries',
      paidBy: 'GPay',
      amountSpend: '80',
      details: 'Water tins',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '2',
      dateOfPurchase: 'Sun Jul 02 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'House rent',
      expenditureType: 'Rent',
      paidBy: 'Online Payment',
      amountSpend: '11000',
      details: 'HDFC Bank Payment',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '3',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Current bill',
      expenditureType: 'Rent',
      paidBy: 'Online Payment',
      amountSpend: '1036',
      details: 'June month current, water, maintenance bill HDFC payment',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '4',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Zerodha shares',
      expenditureType: 'Groceries',
      paidBy: 'GPay',
      amountSpend: '11000',
      details: 'Service bill and pre paid to buy new shares',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '5',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'ETMoney ',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '10000',
      details: 'Mutual funds, missed sips for June and july',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '6',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Car rent',
      expenditureType: 'Rent',
      paidBy: 'GPay',
      amountSpend: '1800',
      details: 'May and June month Car rent money 900and900',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '7',
      dateOfPurchase: 'Mon Jul 10 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Jio mart',
      expenditureType: 'Groceries',
      paidBy: 'GPay',
      amountSpend: '290',
      details:
        'Chings schezwan fried rice masala for geethu at jio mart. Gpay-SBI',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '8',
      dateOfPurchase: 'Wed Jul 05 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Chicken Fried Rice',
      expenditureType: 'Street Foods',
      paidBy: 'GPay',
      amountSpend: '150',
      details: 'Foot @ Office',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '9',
      dateOfPurchase: 'Wed Jul 05 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Water bottle',
      expenditureType: 'Street Foods',
      paidBy: 'GPay',
      amountSpend: '10',
      details: 'Water @ office',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '10',
      dateOfPurchase: 'Wed Jul 05 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Anusha Super Market',
      expenditureType: 'Groceries',
      paidBy: 'GPay',
      amountSpend: '70',
      details: 'Milk packet and 1 curd Packet',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '11',
      dateOfPurchase: 'Thu Jul 06 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Travel',
      expenditureType: 'Rent',
      paidBy: 'GPay',
      amountSpend: '10000',
      details: 'Travel from kakinada 3members, Attaya return ticket ',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '12',
      dateOfPurchase: 'Sun Jul 09 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Meat',
      expenditureType: 'Groceries',
      paidBy: 'GPay',
      amountSpend: '150',
      details:
        'Black Crab on Sunday, black crab not good next time bring only white crabs',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '13',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Gas Cylinder ',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '1185',
      details: 'Gas + service : 1155+30',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '14',
      dateOfPurchase: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Internet Balance',
      expenditureType: 'Fun and Entertainment',
      paidBy: 'Online Payment',
      amountSpend: '239',
      details: 'Jio internet balance for one month',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '15',
      dateOfPurchase: 'Mon Jul 03 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Anusha Super Market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '213',
      details: 'Biscuits',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '16',
      dateOfPurchase: 'Fri Jul 07 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Super Market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '315',
      details:
        'Water Tins+soaps(comfort17, urdh daal, idly nooka) +milk2:80+175+60',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '17',
      dateOfPurchase: 'Tue Jul 04 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Toys',
      expenditureType: 'Fun and Entertainment',
      paidBy: 'Online Payment',
      amountSpend: '196.91',
      details: 'Baby toys cred payment via sbi',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '18',
      dateOfPurchase: 'Wed Jul 05 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Toys',
      expenditureType: 'Fun and Entertainment',
      paidBy: 'Online Payment',
      amountSpend: '86.86',
      details: 'Baby toys cred via sbi',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '19',
      dateOfPurchase: 'Sat Jul 08 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Tiffins',
      expenditureType: 'Street Foods',
      paidBy: 'Online Payment',
      amountSpend: '50',
      details: 'Tiffin in Saturday during house search',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '20',
      dateOfPurchase: 'Sat Jul 08 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Petrol',
      expenditureType: 'Rent',
      paidBy: 'Online Payment',
      amountSpend: '510',
      details: 'Petrol',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '21',
      dateOfPurchase: 'Mon Jul 10 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Tiffins ',
      expenditureType: 'Street Foods',
      paidBy: 'Online Payment',
      amountSpend: '110',
      details: 'Tiffin as joshna gave blood for testing',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '22',
      dateOfPurchase: 'Sat Jul 01 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Super market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '208',
      details: 'Anusha Super market',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '23',
      dateOfPurchase: 'Sun Jul 02 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Internet Bill',
      expenditureType: 'Fun and Entertainment',
      paidBy: 'Online Payment',
      amountSpend: '590',
      details: 'Internet Bill for July month',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '24',
      dateOfPurchase: 'Sun Jul 02 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Baby',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '311',
      details: 'Chicco shampoo for baby 2nos @ amazon',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '25',
      dateOfPurchase: 'Mon Jul 03 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Baby',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '1168.5',
      details: 'Cerelac2, nestum1, similac1 for baby',
      dateCreated: 'Tue Jul 11 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '26',
      dateOfPurchase: 'Wed Jul 12 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Office Food',
      expenditureType: 'Street Foods',
      paidBy: 'Online Payment',
      amountSpend: '70',
      details: 'Double egg Friedrice',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '27',
      dateOfPurchase: 'Wed Jul 12 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Baby',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '1718.55',
      details: 'Similac(3)+Econorm(3)',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '28',
      dateOfPurchase: 'Wed Jul 12 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Super market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '140',
      details: 'No1 Soaps(4)',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '29',
      dateOfPurchase: 'Wed Jul 12 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Online Shopping',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '1011',
      details: 'Amazon - Car Cover for daddy',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '30',
      dateOfPurchase: 'Fri Jul 14 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Super market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '80',
      details: 'Milk',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '31',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Online Shopping',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '1094',
      details: 'Amazon - tripod, baby lotion, recharble batteries + charger',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '32',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Medical Shop',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '260',
      details: 'Feeding bottle 250ml + wide mouth nipple',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '33',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Super market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '108',
      details: 'Milk + Eggs',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '34',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Mechanical Shop',
      expenditureType: 'Rent',
      paidBy: 'Online Payment',
      amountSpend: '1600',
      details: 'Car Bearings repair',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '35',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Super market',
      expenditureType: 'Groceries',
      paidBy: 'Online Payment',
      amountSpend: '32',
      details: '',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '36',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Electronics Shop',
      expenditureType: 'Rent',
      paidBy: 'Online Payment',
      amountSpend: '300',
      details: 'laptop repair service Charges',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '37',
      dateOfPurchase: 'Mon Jul 17 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Tiffins',
      expenditureType: 'Street Foods',
      paidBy: 'Cash',
      amountSpend: '110',
      details: 'Upma Dosa+Idly+Bonda',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '38',
      dateOfPurchase: 'Sun Jul 16 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Veggies',
      expenditureType: 'Groceries',
      paidBy: 'Cash',
      amountSpend: '100',
      details: 'Palak(20)+Bendi(30)+Chikkidi(50)',
      dateCreated: 'Tue Jul 18 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
    {
      index: '39',
      dateOfPurchase: 'Wed Jul 19 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      nameOfPurchase: 'Office Food',
      expenditureType: 'Street Foods',
      paidBy: 'Online Payment',
      amountSpend: '80',
      details: 'Chicken Fried Rice',
      dateCreated: 'Wed Jul 19 2023 00:00:00 GMT+0530 (heure de l’Inde)',
      expenditureId: '',
      isSynced: '',
    },
  ],
};
